# Generated by Django 5.0.6 on 2024-06-02 00:13

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('ID', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='El ID de la orden debe comenzar con C seguido de 4 dígitos.', regex='^C[0-9]{4}$')])),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_limite', models.DateField()),
                ('plazo_pago', models.CharField(default='30 días', max_length=20)),
                ('estado', models.CharField(choices=[('Enviado', 'Enviado'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Enviado', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ID', models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El ID debe tener hasta 6 caracteres, incluyendo letras y números.', regex='^[A-Za-z0-9]{1,6}$')])),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('ID', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El ID del proveedor debe comenzar con P seguido de 4 dígitos.', regex='^P[0-9]{4}$')])),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', django_countries.fields.CountryField(max_length=2)),
                ('direccion', models.CharField(default='Desconocido', max_length=255)),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('vendedor_nombre', models.CharField(max_length=100)),
                ('vendedor_apellido', models.CharField(max_length=100)),
                ('vendedor_puesto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID', models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El ID debe comenzar con G o E seguido de 3 números.', regex='^[GE][0-9]{3}$')])),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='La contraseña debe tener entre 4 y 10 caracteres.', regex='^.{4,10}$')])),
                ('rol', models.CharField(choices=[('Gerente', 'Gerente'), ('Empleado', 'Empleado')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='clases.ordencompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='clases.proveedor'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='clases.proveedor'),
        ),
    ]
