# Generated by Django 5.0.6 on 2024-06-06 23:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleorden',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='producto',
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_orden', to='clases.ordencompra'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Número de teléfono inválido.', regex='^\\+?[\\d-]{1,15}$')]),
        ),
        migrations.CreateModel(
            name='productosDetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_detalle_orden', to='clases.ordencompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.producto')),
            ],
        ),
    ]
